Annotations for `nacl.bindings.crypto_box` (#706)
* Annotations for `nacl.bindings.crypto_box`

This introduced a few errors in nacl.public which I wasn't sure how to
suppress. AFAICS both will raise a TypeError at run-time, so I
suppressed mypy's errors. I wasn't completely satisfied with this; I
very much welcome input here!

Box._shared_key
===============

The first error mypy reported was

```
src/nacl/public.py:193: error: Incompatible types in assignment (expression has type "None", variable has type "bytes")  [assignment]
```

referring to `self._shared_key`. I resolved this by marking
`_shared_key: Optional[bytes]` to cover both cases in the constructor.
But doing this introduced two new errors:

```
src/nacl/public.py:236: error: Argument 3 to "crypto_box_afternm" has incompatible type "Optional[bytes]"; expected "bytes"  [arg-type]
src/nacl/public.py:278: error: Argument 3 to "crypto_box_open_afternm" has incompatible type "Optional[bytes]"; expected "bytes"  [arg-type]
```

Which correspond to the annotations I added to `crypto_box_afternm` and
`crypto_box_open_afternm`'s `k` argument. Both docstrings say that `k`
should be a `bytes` instance, and go on to inspect `len(k)`. Therefore,
calling this with `k=None` will raise a `TypeError`.

SealedBox._private_key
======================

Similarly, I also now have the complaint

```
src/nacl/public.py:382: error: Argument 3 to "crypto_box_seal_open" has incompatible type "Optional[bytes]"; expected "bytes"  [arg-type
```

because `self._private_key` may be `None`. In this instance there is an
explicit `ensure` check in `crypto_box_seal_open` which will raise a
TypeError.

I also adjusted the SealedBox docstring to match its `__init__` method,
which appears to be the convention (judging by the other classes in this
file).

* Decrypting without a private key raises bespoke TypeError

* Teach mypy that SealedBox can only decrypt with a private key

* Ensure that `Box._shared_key` is never `None`